### PR TITLE
 Responsive design of whole website

### PR DESCRIPTION
**Pull request by kishanlalchoudhary**
Made website responsive for all devices

### CODE REVIEW

**Comment by kishanlalchoudhary** [comment]
pls merge as soon as possible if you like under hacktoberfest

**Comment by kishanlalchoudhary** [comment]
Screenshot (49)

**Comment by kishanlalchoudhary** [comment]
pls add hactoberfest tag

**Comment by aditya-1404** [comment]
> pls add hactoberfest tag

already added

**Comment by kishanlalchoudhary** [comment]
can you add hactoberfest-accepted tag pls

**Comment by kishanlalchoudhary** [comment]
Add hactoberfest - accepted to my pr

**Pull request merged**
